name: build

on:
  push: 
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      - name: GoLang Test
        uses: n8maninger/action-golang-test@v1
        with:
          skip-go-install: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          skip-go-installation: true
